apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bee-travels-ingress
spec:
  tls:
    - hosts: 
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.global.ingress.secret }}
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.name }}
                port:
                  number: 80