apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrental
  labels:
    run: carrental
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: carrental
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: carrental
    spec:
      containers:
      - image: beetravels/carrental-v1:node-v1.0.0
        imagePullPolicy: Always
        name: carrental
        env:
          - name: PORT
            value: "9102"
          - name: HOST_IP
            value: carrental
          - name: SCHEME
            value: http
          - name: LOG_LEVEL
            value: info
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
      
