apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  labels:
    run: hotel
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hotel
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hotel
    spec:
      containers:
      - image: beetravels/hotel-v2:node-v1.0.0
        imagePullPolicy: Always
        name: hotel
        env:
          - name: PORT
            value: "9101"
          - name: HOST_IP
            value: hotel
          - name: SCHEME
            value: http
          - name: DATABASE
            value: postgres
          - name: MONGO_CONNECTION_URL
            value: mongodb://admin:admin@mongo:27017
          - name: COUCH_CLOUDANT_CONNECTION_URL
            value: http://admin:admin@couch:5984
          - name: PG_HOST
            value: bee-travels-db-postgresql
          - name: PG_USER
            value: postgres
          - name: PG_PASSWORD
            value: Oyg9YxwKmm
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      
