apiVersion: apps/v1
kind: Deployment
metadata:
  name: bee-ui
  labels:
    run: bee-ui
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bee-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: bee-ui
    spec:
      containers:
      - image: beetravels/ui:node-v1.0.0
        imagePullPolicy: Always
        name: bee-ui
        env:
          - name: PORT
            value: "9000"
          - name: NODE_ENV
            value: production
          - name: DESTINATION_URL
            value: https://b45fd817a6ca40988ef20e6ed948a44f-167772166-simba09b.environments.katacoda.com/destination
          - name: CAR_URL
            value: https://b45fd817a6ca40988ef20e6ed948a44f-167772166-simba09b.environments.katacoda.com/carrental
          - name: HOTEL_URL
            value: https://b45fd817a6ca40988ef20e6ed948a44f-167772166-simba09b.environments.katacoda.com/hotel
          - name: CURRENCY_EXCHANGE_URL
            value: https://b45fd817a6ca40988ef20e6ed948a44f-167772166-simba09b.environments.katacoda.com/currencyexchange
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 256Mi
        #   requests:
        #     cpu: 100m
        #     memory: 256Mi
      restartPolicy: Always