deployment:
  name: bee-ui
  version: v1
  replicas: 1
  image: beetravels/ui
  envs: 
    PORT: 9000
    DESTINATION_URL: http://destination
    HOTEL_URL: http://hotel
    CURRENCY_EXCHANGE_URL: http://currencyexchange
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi
service:
  name: bee-ui
  type: ClusterIP
  port: 80
  protocol: TCP
  targetPort: 9000
ingress:
  name: bee-ui